export const FETCH_CART_LOADING = "FETCH_CART_LOADING";
export const FETCH_CART_ERROR = "FETCH_CART_ERROR";
export const FETCH_CART_DATA = "FETCH_CART_DATA";

export const FETCH_UPDATE_LOADING = "FETCH_UPDATE_LOADING";
export const FETCH_UPDATE_ERROR = "FETCH_UPDATE_ERROR";
export const FETCH_UPDATE_STATUS = "FETCH_UPDATE_STATUS";
