export const FETCH_POSTS_LOADING = "FETCH_POSTS_LOADING";
export const FETCH_POSTS_ERROR = "FETCH_POSTS_ERROR";
export const FETCH_POSTS_DATA = "FETCH_POSTS_DATA";

export const FETCH_SINGLE_POSTS_LOADING = "FETCH_SINGLE_POSTS_LOADING";
export const FETCH_SINGLE_POSTS_ERROR = "FETCH_SINGLE_POSTS_ERROR";
export const FETCH_SINGLE_POSTS_DATA = "FETCH_SINGLE_POSTS_DATA";

export const UPLOAD_LOADING = "UPLOAD_LOADING";
export const UPLOAD_ERROR = "UPLOAD_ERROR";
export const UPLOAD_SUCCESS = "UPLOAD_SUCCESS";
